version: "3"

services:
  drupal:
    build: .
    image: nmallas/custom-drupal
    ports:
      - 8080:80
    depends_on:
      - postgres

  postgres:
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - drupal-data:/var/lib/postgresql/data
    image: postgres:9.6

volumes:
  drupal-data:
