"""update package table

Revision ID: 6209577e08fe
Revises: a99fa8edcd06
Create Date: 2020-09-17 17:19:23.620470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6209577e08fe'
down_revision = 'a99fa8edcd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column(
        'express_shipping', sa.Boolean(), nullable=True))
    op.drop_column('packages', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column(
        'location', sa.VARCHAR(length=255),
        autoincrement=False, nullable=True))
    op.drop_column('packages', 'express_shipping')
    # ### end Alembic commands ###
